VipAuction.Web/Models/UserViewModel.cs
// <copyright file="UserViewModel.cs" company="SoftServe">
// Copyright (c) 2013 All Rights Reserved
// </copyright>
// <author>Baboshkin Igor</author>
// <date>29.03.2013 02:21:49</date>


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SoftServe.VipAuction.Web.Models
{
    /// <summary>
    /// User view model
    /// </summary>
    public class UserViewModel
    {
        public Int32 UserId { get; set; }

        [StringLength(20, MinimumLength = 1)]
        [DataType(DataType.Text)]
        public String FirstName { get; set; }

        [StringLength(20, MinimumLength = 1)]
        [DataType(DataType.Text)]
        public String LastName { get; set; }

        public Int32 Experience { get; set; }

        public Byte Discount { get; set; }

        public Byte Status { get; set; }

        public Boolean IsBlocked { get; set; }
    }
}

VipAuction.Web/Controllers/LotController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using Ocorola.Module.Infrastructure;
using SoftServe.VipAuction.Modules.VipAuctionServerModule.Models;
using SoftServe.VipAuction.Modules.VipAuctionServerModule.Enums;
using SoftServe.VipAuction.Modules.VipAuctionServerModule.Contracts;
using SoftServe.VipAuction.Modules.VipAuctionServerModule;
using SoftServe.VipAuction.Web.Helpers;
using SoftServe.VipAuction.Web.Models;

namespace SoftServe.VipAuction.Web.Controllers
{
    public class LotController : Controller
    {
        private ILotContract mDataController = AuctionLogicContainer.Instance.GetService<ILotContract>();

        public ActionResult Index(string id)
        {
            if (string.Compare(id, "all", true) == 0)
                id = "-1";

            ViewBag.userId = int.Parse(id);

            return View();
        }

        public ActionResult ViewLot(int id, int role)
        {
            if (role == 0)
            {
                ViewBag.admin = false;

            }
            else
            {
                ViewBag.admin = true;
            }

            var lotView = ViewModelsMapper.Map<Lot, ViewLotViewModel>(mDataController.GetLot(id));

            return View(lotView);
        }

        public JsonResult GetLots(int id, string searchedText, [DataSourceRequest] DataSourceRequest request)
        {
            IEnumerable<Lot> lots = null;

            if(id>-1)
                lots = mDataController.GetUserLots(id, searchedText);
            else
                lots = mDataController.GetAvailableLots(searchedText);

            var lotsViewModel = ViewModelsMapper.Map<IEnumerable<Lot>, IEnumerable<CatalogViewModel>>(lots);

            if (lotsViewModel == null)
                lotsViewModel = new CatalogViewModel[] { };

            return Json(lotsViewModel.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        [AcceptVerbs("POST")]
        public JsonResult GetLastLots([DataSourceRequest] DataSourceRequest request)
        {
            var lastLots = mDataController.GetAvailableLots().OrderByDescending(l => l.LotId).Take(3);
            var lastLotsViewModel = ViewModelsMapper.Map<IEnumerable<Lot>, IEnumerable<LastPublishedLotViewModel>>(lastLots);

            if (lastLotsViewModel == null)
                lastLotsViewModel = new LastPublishedLotViewModel[] { };

            return Json(lastLotsViewModel.ToDataSourceResult(request));
        }

        [AcceptVerbs("POST")]
        public void AddLot(CreateNewLotViewModel lot)
        {
            if ((int)Session["UserId"] == -1) return;
            Lot newLot = new Lot();

            ViewModelsMapper.Map<CreateNewLotViewModel, Lot>(lot, newLot);

            if (newLot == null) return;

            newLot.State = eLotStateType.NotActivated;
            newLot.UserId = (int)Session["UserId"];
            mDataController.CreateLot(newLot);
        }

        [AcceptVerbs("POST")]
        public JsonResult GetApproveLots(string searchedText, [DataSourceRequest] DataSourceRequest request)
        {
            var approveLots = mDataController.GetNotActivatedLots(searchedText);
            var approveLotsViewModel = ViewModelsMapper.Map<IEnumerable<Lot>, IEnumerable<ApproveLotViewModel>>(approveLots);

            if (approveLotsViewModel == null)
                approveLotsViewModel = new ApproveLotViewModel[] { };

            return Json(approveLotsViewModel.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        [AcceptVerbs("POST")]
        public void ActivateLot(int lotId)
        {
            mDataController.ActivateLot(lotId);
        }

        [AcceptVerbs("POST")]
        public void ChangeLotState(ChangeLotStateViewModel lot)
        {
            switch ((eLotStateType)lot.State)
            {
                case eLotStateType.Blocked:
                    mDataController.BlockLot(lot.LotId);
                    break;
                case eLotStateType.Published:
                    mDataController.ActivateLot(lot.LotId);
                    break;
                case eLotStateType.Canceled:
                    mDataController.CanselLot(lot.LotId);
                    break;
                case eLotStateType.Sold:
                    break;
                case eLotStateType.Closed:
                    break;
                default:
                    break;
            }
        }
    }
}

VipAuction.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kendo.Mvc.UI;
using Ocorola.Module.Infrastructure;

using Kendo.Mvc.Extensions;

using SoftServe.VipAuction.Modules.VipAuctionServerModule.Models;
using SoftServe.VipAuction.Modules.VipAuctionServerModule.Enums;
using SoftServe.VipAuction.Modules.VipAuctionServerModule.Contracts;
using SoftServe.VipAuction.Modules.VipAuctionServerModule;
using SoftServe.VipAuction.Web.Helpers;
using SoftServe.VipAuction.Web.Models;

namespace SoftServe.VipAuction.Web.Controllers
{
    public class UserController : Controller
    {
        private IUserContract mDataController = AuctionLogicContainer.Instance.GetService<IUserContract>();

        public ActionResult MyProfile(int id)
        {
            if (id <= 0) id = (int)Session["UserId"];

            var profile = ViewModelsMapper.Map<UserProfile, UserProfileViewModel>(mDataController.GetProfile(id));
            return View(profile);
        }

        public JsonResult GetUsers(string searchedText, [DataSourceRequest] DataSourceRequest request)
        {
            var users = ViewModelsMapper.Map<IEnumerable<UserProfile>, IEnumerable<UserViewModel>>(mDataController.ViewUsers());

            if (users == null)
                users = new UserViewModel[] { };

            return Json(users.ToDataSourceResult(request));
        }

        [AcceptVerbs("POST")]
        public void UpdateUser(EditProfileViewModel user)
        {
            var profile = ViewModelsMapper.Map<EditProfileViewModel, UserProfile>(user);

            if (profile == null) return;
            mDataController.SaveProfile(profile);
        }

        
    }
}

VipAuction.Web/Views/User/MyProfile.cshtml
@model SoftServe.VipAuction.Web.Models.UserProfileViewModel
@Scripts.Render("~/bundles/myProfile")
@{
    Layout = null;
    ViewBag.Title = "MyProfile";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>LoginForm</title>
</head>
<body>
    <div class="formMain">
        <ul class="fieldlist">
            <li>
                <label for="flogin">@ViewRes.UserResource.Login</label>
                @if ((int)Session["UserId"] == Model.UserId)
                {
                    <input id="flogin" type="text" readonly="true" value="@Model.UserName" class="editableValue k-textbox"/>
                    <input id="floginTemp" type="hidden" value="@Model.UserName"/>
                }
                else
                {
                    <label id="flogin">@Model.UserName</label>
                }
            </li>
            <li>
                <label for="ffirstname">@ViewRes.UserResource.FirstName</label>
                @if ((int)Session["UserId"] == Model.UserId)
                {
                    <input id="ffirstname" type="text" readonly="true" value="@Model.FirstName" class="editableValue k-textbox"/>
                    <input id="ffirstnameTemp" type="hidden" value="" />
                }
                else
                {
                    <label id="ffirstname">@Model.FirstName</label>
                }
            </li>
            <li>
                <label for="flasttname">@ViewRes.UserResource.LastName</label>
                @if ((int)Session["UserId"] == Model.UserId)
                {
                    <input id="flasttname" type="text" readonly="true" value="@Model.LastName" class="editableValue k-textbox"/>
                    <input id="flasttnameTemp" type="hidden" value="" />
                }
                else
                {
                    <label id="flasttname">@Model.LastName</label>
                }
            </li>
            <li>
                <label for="femail">@ViewRes.UserResource.Email</label>
                @if ((int)Session["UserId"] == Model.UserId)
                {
                    <input id="femail" type="text" readonly="true" value="@Model.Email" class="editableValue k-textbox"/>
                    <input id="femailTemp" type="hidden" value="" />
                }
                else
                {
                    <label id="femail">@Model.Email</label>
                }
            </li>
        </ul>
        <hr />
        <ul class="fieldlist">
            <li>
                <label for="fstatus">@ViewRes.UserResource.Status</label>
                <label id="fstatus">@Model.Status</label>
            </li>
            <li>
                <label for="fblocked">Blocked</label>
                <!-- Change true on yes and false on no in view model -->
                <label id="fblocked">@Model.IsBlocked.ToString()</label>
            </li>
        </ul>
        <hr />
        <ul class="fieldlist">
            <li>
                <label for="fbalance">@ViewRes.UserResource.Balance</label>
                <label id="fbalance">$@Model.Balance</label>
            </li>
            <li>
                <label for="fptsbymonth">@ViewRes.UserResource.PoinsByMonth</label>
                <label id="fptsbymonth">@Model.PoinsByMonth</label>
            </li>
            <li>
                <label for="ftotalpts">@ViewRes.UserResource.TotalPoints</label>
                <label id="ftotalpts">@Model.TotalPoints</label>
            </li>
            <li>
                <label for="fdiscount">@ViewRes.UserResource.Discount</label>
                <label id="fdiscount">@Model.Discount</label>
            </li>
            <li>
                <label for="fexpirience">@ViewRes.UserResource.Experience</label>
                <label id="fexpirience">@Model.Experience</label>
            </li>
        </ul>

        <hr />

        <div class="toolbar">
            @if ((int)Session["UserId"] == Model.UserId)
            {
                <input id="btnedit" type="button" class="k-button toolbutton" value="@ViewRes.ButtonResource.EditButton" 
                onclick="myProfile.btnEditClick('@ViewRes.ButtonResource.SaveButton', '@ViewRes.ButtonResource.CancelButton',
                                                '@ViewRes.ButtonResource.EditButton', '@ViewRes.ButtonResource.CloseButton', @(Model.UserId))"/>
                <input id="btnlots" type="button" class="k-button toolbutton" value="@ViewRes.ButtonResource.MyLotsButton" 
                onclick="window.location.href = '@(Url.Action("Index", "Lot", new { id = Model.UserId }))    '"/>
            }
            else
            if ((int)Session["RoleId"] == 1)
            {
                <input type="button" id="AdminUserDetails_block" class="k-button toolbutton" 
                value="@if (Model.IsBlocked)
                       {<text>@ViewRes.ButtonResource.UnblockButton</text>}
                       else
                       {<text>@ViewRes.ButtonResource.BlockButton</text>}"  
                    onclick="myProfile.btnBlockClick('@ViewRes.ButtonResource.BlockButton', '@ViewRes.ButtonResource.UnblockButton',
                                            '@(Model.UserId)',  '@(Model.UserName)', '@(Model.FirstName)', '@(Model.LastName)', '@(Model.Email)')"/>
            }
            <input id="btnclose" type="button" class="k-button toolbutton" value="@ViewRes.ButtonResource.CloseButton" 
            onclick="myProfile.btnCLoseClick('@ViewRes.ButtonResource.EditButton', '@ViewRes.ButtonResource.CloseButton', @(Model.UserId))" />
        </div>
    </div>

    <script>
    </script>
</body>
</html>